# Generated by Django 3.1.1 on 2020-09-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id_buku', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('tahun', models.IntegerField(max_length=4)),
            ],
        ),
    ]
