# Generated by Django 3.1.1 on 2020-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbti_app', '0002_auto_20200919_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='buku',
            name='id_buku',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buku',
            name='tahun',
            field=models.CharField(max_length=255),
        ),
    ]
