# Generated by Django 3.1.3 on 2020-11-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbti_app', '0004_mahasiswa_peminjaman'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peminjaman',
            old_name='id_mahasiswa',
            new_name='npm',
        ),
    ]
