# Generated by Django 3.1.5 on 2021-01-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbti_app', '0005_auto_20201117_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjaman',
            name='id_buku',
        ),
        migrations.RemoveField(
            model_name='peminjaman',
            name='npm',
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
        migrations.DeleteModel(
            name='Peminjaman',
        ),
    ]
